server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 6s

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cache:
  redirect-ttl-hours: 24

app:
  base-url: ${BASE_URL}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}

  short-code:
    length: 7
    max-retry-attempts: 5

  url:
    default-expiry-days: 30

scheduler:
  url-expiry-cron: "0 0 * * * *"
  deleted-url-cleanup-cron: "0 0 2 * * *"
  deleted-url-retention-days: 30
  token-cleanup-cron: "0 30 2 * * *"
  expiry-reminder-cron: "0 0 9 * * *"
  expiry-reminder-hours: 24

rate-limit:
  login:
    requests: 5
    duration: 60

  register:
    requests: 3
    duration: 3600

  forgot-password:
    requests: 3
    duration: 3600

  refresh-token:
    requests: 20
    duration: 60

  redirect:
    requests: 100
    duration: 60

  create-url:
    requests: 50
    duration: 3600

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    org.flywaydb: DEBUG
    com.aryan.ziplink: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG #before pushing to github change it to  DEBUG
    org.springframework.cache: TRACE